export const LOGIN = '/login'
export const HOME = '/'
export const CREATE_ACCOUNT = '/create-account'
export const ACCOUNT_PASSWORD = '/account-password'
export const ACCOUNT_CREATED = '/account-created'
export const ACCOUNT_BACKUP = '/account-backup'
export const ACCOUNT = '/account'
export const ACCOUNT_RESTORE = '/account-restore'
